"""initial_schema

Revision ID: 7c9d49d2bbf7
Revises:
Create Date: 2026-03-10 20:09:15.261236

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c9d49d2bbf7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("lift_type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("video_url", sa.Text(), nullable=False),
        sa.Column("video_path", sa.Text(), nullable=True),
        sa.Column("author", sa.String(length=100), nullable=False),
        sa.Column("post_score", sa.Integer(), nullable=False),
        sa.Column("created_utc", sa.DateTime(), nullable=False),
        sa.Column("scraped_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_posts_lift_type"), "posts", ["lift_type"], unique=False)
    op.create_table(
        "comments",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("post_id", sa.String(length=20), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("author", sa.String(length=100), nullable=False),
        sa.Column("created_utc", sa.DateTime(), nullable=False),
        sa.Column("is_top_level", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_comments_post_id"), "comments", ["post_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_comments_post_id"), table_name="comments")
    op.drop_table("comments")
    op.drop_index(op.f("ix_posts_lift_type"), table_name="posts")
    op.drop_table("posts")
    # ### end Alembic commands ###
